//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int oi_id { get; set; }
        public int quantity { get; set; }
        public int furniture_id { get; set; }
        public int user_id { get; set; }
    
        public virtual MenuItems MenuItems { get; set; }
        public virtual Users Users { get; set; }
    }
}
